-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Hospital readmissions (Diabetes 130-US hospitals) - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/` and executed on a serverless SQL warehouse by `scripts/databricks_deploy.py`.
-- MAGIC
-- MAGIC 1. Upload the raw file(s) to the Unity Catalog volume `/Volumes/workspace/da_learn_08/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
-- MAGIC 3. Cells: config -> 01 staging (`read_files`, all STRING) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.

-- COMMAND ----------

-- Config: change catalog / schema here (and in the dashboard JSON) if needed
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_08;
USE CATALOG workspace;
USE SCHEMA da_learn_08;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging - all columns as STRING (`inferColumnTypes => false`); casting happens in 02

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_encounters AS
SELECT * EXCEPT (`glyburide-metformin`, `glipizide-metformin`, `glimepiride-pioglitazone`, `metformin-rosiglitazone`, `metformin-pioglitazone`),
       `glyburide-metformin` AS glyburide_metformin,
       `glipizide-metformin` AS glipizide_metformin,
       `glimepiride-pioglitazone` AS glimepiride_pioglitazone,
       `metformin-rosiglitazone` AS metformin_rosiglitazone,
       `metformin-pioglitazone` AS metformin_pioglitazone
FROM read_files('/Volumes/workspace/da_learn_08/raw/diabetic_data.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_ids_mapping AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_08/raw/IDS_mapping.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; runs on DuckDB via 00_duckdb_compat.sql shims)

CREATE OR REPLACE TABLE cln_encounters AS
WITH typed AS (
  SELECT
    TRY_CAST(encounter_id AS BIGINT)                                   AS encounter_id,
    TRY_CAST(patient_nbr AS BIGINT)                                    AS patient_nbr,
    CASE WHEN trim(race) IN ('?', '') THEN NULL
         WHEN trim(race) = 'AfricanAmerican' THEN 'African American'
         ELSE trim(race) END                                           AS race,
    CASE WHEN trim(gender) IN ('Male', 'Female') THEN trim(gender) ELSE NULL END AS gender,
    CASE WHEN trim(age) LIKE '[%)' THEN replace(replace(trim(age), '[', ''), ')', '') ELSE NULL END AS age_group,
    CASE WHEN trim(weight) IN ('?', '') THEN NULL ELSE replace(replace(trim(weight), '[', ''), ')', '') END AS weight_band,
    TRY_CAST(admission_type_id AS INT)                                 AS admission_type_id,
    TRY_CAST(discharge_disposition_id AS INT)                          AS discharge_disposition_id,
    TRY_CAST(admission_source_id AS INT)                               AS admission_source_id,
    TRY_CAST(time_in_hospital AS INT)                                  AS time_in_hospital,
    CASE WHEN trim(payer_code) IN ('?', '') THEN NULL ELSE trim(payer_code) END AS payer_code,
    CASE WHEN trim(medical_specialty) IN ('?', '') THEN NULL ELSE trim(medical_specialty) END AS medical_specialty,
    TRY_CAST(num_lab_procedures AS INT)                                AS num_lab_procedures,
    TRY_CAST(num_procedures AS INT)                                    AS num_procedures,
    TRY_CAST(num_medications AS INT)                                   AS num_medications,
    TRY_CAST(number_outpatient AS INT)                                 AS number_outpatient,
    TRY_CAST(number_emergency AS INT)                                  AS number_emergency,
    TRY_CAST(number_inpatient AS INT)                                  AS number_inpatient,
    CASE WHEN trim(diag_1) IN ('?', '') THEN NULL ELSE trim(diag_1) END AS diag_1,
    CASE WHEN trim(diag_2) IN ('?', '') THEN NULL ELSE trim(diag_2) END AS diag_2,
    CASE WHEN trim(diag_3) IN ('?', '') THEN NULL ELSE trim(diag_3) END AS diag_3,
    TRY_CAST(diag_1 AS DOUBLE)                                         AS diag_1_num,   -- NULL for V / E codes
    TRY_CAST(diag_2 AS DOUBLE)                                         AS diag_2_num,
    TRY_CAST(diag_3 AS DOUBLE)                                         AS diag_3_num,
    TRY_CAST(number_diagnoses AS INT)                                  AS number_diagnoses,
    CASE WHEN trim(max_glu_serum) IN ('None', '?', '') THEN 'Not measured' ELSE trim(max_glu_serum) END AS max_glu_serum,
    CASE WHEN trim(A1Cresult) IN ('None', '?', '') THEN 'Not measured' ELSE trim(A1Cresult) END AS a1c_result,
    CASE WHEN trim(metformin) IN ('No', 'Steady', 'Up', 'Down') THEN trim(metformin) ELSE NULL END AS med_metformin,
    CASE WHEN trim(repaglinide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(repaglinide) ELSE NULL END AS med_repaglinide,
    CASE WHEN trim(nateglinide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(nateglinide) ELSE NULL END AS med_nateglinide,
    CASE WHEN trim(chlorpropamide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(chlorpropamide) ELSE NULL END AS med_chlorpropamide,
    CASE WHEN trim(glimepiride) IN ('No', 'Steady', 'Up', 'Down') THEN trim(glimepiride) ELSE NULL END AS med_glimepiride,
    CASE WHEN trim(acetohexamide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(acetohexamide) ELSE NULL END AS med_acetohexamide,
    CASE WHEN trim(glipizide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(glipizide) ELSE NULL END AS med_glipizide,
    CASE WHEN trim(glyburide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(glyburide) ELSE NULL END AS med_glyburide,
    CASE WHEN trim(tolbutamide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(tolbutamide) ELSE NULL END AS med_tolbutamide,
    CASE WHEN trim(pioglitazone) IN ('No', 'Steady', 'Up', 'Down') THEN trim(pioglitazone) ELSE NULL END AS med_pioglitazone,
    CASE WHEN trim(rosiglitazone) IN ('No', 'Steady', 'Up', 'Down') THEN trim(rosiglitazone) ELSE NULL END AS med_rosiglitazone,
    CASE WHEN trim(acarbose) IN ('No', 'Steady', 'Up', 'Down') THEN trim(acarbose) ELSE NULL END AS med_acarbose,
    CASE WHEN trim(miglitol) IN ('No', 'Steady', 'Up', 'Down') THEN trim(miglitol) ELSE NULL END AS med_miglitol,
    CASE WHEN trim(troglitazone) IN ('No', 'Steady', 'Up', 'Down') THEN trim(troglitazone) ELSE NULL END AS med_troglitazone,
    CASE WHEN trim(tolazamide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(tolazamide) ELSE NULL END AS med_tolazamide,
    CASE WHEN trim(examide) IN ('No', 'Steady', 'Up', 'Down') THEN trim(examide) ELSE NULL END AS med_examide,
    CASE WHEN trim(citoglipton) IN ('No', 'Steady', 'Up', 'Down') THEN trim(citoglipton) ELSE NULL END AS med_citoglipton,
    CASE WHEN trim(insulin) IN ('No', 'Steady', 'Up', 'Down') THEN trim(insulin) ELSE NULL END AS med_insulin,
    CASE WHEN trim(glyburide_metformin) IN ('No', 'Steady', 'Up', 'Down') THEN trim(glyburide_metformin) ELSE NULL END AS med_glyburide_metformin,
    CASE WHEN trim(glipizide_metformin) IN ('No', 'Steady', 'Up', 'Down') THEN trim(glipizide_metformin) ELSE NULL END AS med_glipizide_metformin,
    CASE WHEN trim(glimepiride_pioglitazone) IN ('No', 'Steady', 'Up', 'Down') THEN trim(glimepiride_pioglitazone) ELSE NULL END AS med_glimepiride_pioglitazone,
    CASE WHEN trim(metformin_rosiglitazone) IN ('No', 'Steady', 'Up', 'Down') THEN trim(metformin_rosiglitazone) ELSE NULL END AS med_metformin_rosiglitazone,
    CASE WHEN trim(metformin_pioglitazone) IN ('No', 'Steady', 'Up', 'Down') THEN trim(metformin_pioglitazone) ELSE NULL END AS med_metformin_pioglitazone,
    CASE WHEN trim(change) = 'Ch' THEN 1 WHEN trim(change) = 'No' THEN 0 ELSE NULL END AS med_change_flag,
    CASE WHEN trim(diabetesMed) = 'Yes' THEN 1 WHEN trim(diabetesMed) = 'No' THEN 0 ELSE NULL END AS diabetes_med_flag,
    CASE WHEN trim(readmitted) IN ('<30', '>30', 'NO') THEN trim(readmitted) ELSE NULL END AS readmitted
  FROM stg_encounters
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY encounter_id ORDER BY patient_nbr) AS rn
  FROM typed
  WHERE encounter_id IS NOT NULL
), first_enc AS (
  SELECT encounter_id, ROW_NUMBER() OVER (PARTITION BY patient_nbr ORDER BY encounter_id) AS patient_encounter_seq
  FROM ranked WHERE rn = 1
), bounds AS (
  SELECT
    percentile_approx(CAST(num_medications AS DOUBLE), 0.25)    AS med_q1,
    percentile_approx(CAST(num_medications AS DOUBLE), 0.75)    AS med_q3,
    percentile_approx(CAST(num_lab_procedures AS DOUBLE), 0.25) AS lab_q1,
    percentile_approx(CAST(num_lab_procedures AS DOUBLE), 0.75) AS lab_q3
  FROM ranked WHERE rn = 1
), enriched AS (
  SELECT r.*, f.patient_encounter_seq,
    CASE
    WHEN r.diag_1 IS NULL THEN 'Missing'
    WHEN r.diag_1 LIKE 'V%' OR r.diag_1 LIKE 'E%' THEN 'Other'
    WHEN r.diag_1 LIKE '250%' THEN 'Diabetes'
    WHEN (r.diag_1_num >= 390 AND r.diag_1_num < 460) OR floor(r.diag_1_num) = 785 THEN 'Circulatory'
    WHEN (r.diag_1_num >= 460 AND r.diag_1_num < 520) OR floor(r.diag_1_num) = 786 THEN 'Respiratory'
    WHEN (r.diag_1_num >= 520 AND r.diag_1_num < 580) OR floor(r.diag_1_num) = 787 THEN 'Digestive'
    WHEN (r.diag_1_num >= 580 AND r.diag_1_num < 630) OR floor(r.diag_1_num) = 788 THEN 'Genitourinary'
    WHEN r.diag_1_num >= 800 AND r.diag_1_num < 1000 THEN 'Injury'
    WHEN r.diag_1_num >= 710 AND r.diag_1_num < 740 THEN 'Musculoskeletal'
    WHEN r.diag_1_num >= 140 AND r.diag_1_num < 240 THEN 'Neoplasms'
    ELSE 'Other' END AS diag_1_group,
    CASE
    WHEN r.diag_2 IS NULL THEN 'Missing'
    WHEN r.diag_2 LIKE 'V%' OR r.diag_2 LIKE 'E%' THEN 'Other'
    WHEN r.diag_2 LIKE '250%' THEN 'Diabetes'
    WHEN (r.diag_2_num >= 390 AND r.diag_2_num < 460) OR floor(r.diag_2_num) = 785 THEN 'Circulatory'
    WHEN (r.diag_2_num >= 460 AND r.diag_2_num < 520) OR floor(r.diag_2_num) = 786 THEN 'Respiratory'
    WHEN (r.diag_2_num >= 520 AND r.diag_2_num < 580) OR floor(r.diag_2_num) = 787 THEN 'Digestive'
    WHEN (r.diag_2_num >= 580 AND r.diag_2_num < 630) OR floor(r.diag_2_num) = 788 THEN 'Genitourinary'
    WHEN r.diag_2_num >= 800 AND r.diag_2_num < 1000 THEN 'Injury'
    WHEN r.diag_2_num >= 710 AND r.diag_2_num < 740 THEN 'Musculoskeletal'
    WHEN r.diag_2_num >= 140 AND r.diag_2_num < 240 THEN 'Neoplasms'
    ELSE 'Other' END AS diag_2_group,
    CASE
    WHEN r.diag_3 IS NULL THEN 'Missing'
    WHEN r.diag_3 LIKE 'V%' OR r.diag_3 LIKE 'E%' THEN 'Other'
    WHEN r.diag_3 LIKE '250%' THEN 'Diabetes'
    WHEN (r.diag_3_num >= 390 AND r.diag_3_num < 460) OR floor(r.diag_3_num) = 785 THEN 'Circulatory'
    WHEN (r.diag_3_num >= 460 AND r.diag_3_num < 520) OR floor(r.diag_3_num) = 786 THEN 'Respiratory'
    WHEN (r.diag_3_num >= 520 AND r.diag_3_num < 580) OR floor(r.diag_3_num) = 787 THEN 'Digestive'
    WHEN (r.diag_3_num >= 580 AND r.diag_3_num < 630) OR floor(r.diag_3_num) = 788 THEN 'Genitourinary'
    WHEN r.diag_3_num >= 800 AND r.diag_3_num < 1000 THEN 'Injury'
    WHEN r.diag_3_num >= 710 AND r.diag_3_num < 740 THEN 'Musculoskeletal'
    WHEN r.diag_3_num >= 140 AND r.diag_3_num < 240 THEN 'Neoplasms'
    ELSE 'Other' END AS diag_3_group,
    (CASE WHEN med_metformin IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_repaglinide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_nateglinide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_chlorpropamide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glimepiride IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_acetohexamide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glipizide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glyburide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_tolbutamide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_pioglitazone IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_rosiglitazone IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_acarbose IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_miglitol IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_troglitazone IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_tolazamide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_examide IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_citoglipton IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_insulin IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glyburide_metformin IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glipizide_metformin IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glimepiride_pioglitazone IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_metformin_rosiglitazone IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_metformin_pioglitazone IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END) AS n_diabetes_meds,
    (CASE WHEN med_metformin IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_repaglinide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_nateglinide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_chlorpropamide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glimepiride IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_acetohexamide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glipizide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glyburide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_tolbutamide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_pioglitazone IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_rosiglitazone IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_acarbose IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_miglitol IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_troglitazone IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_tolazamide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_examide IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_citoglipton IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_insulin IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glyburide_metformin IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glipizide_metformin IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_glimepiride_pioglitazone IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_metformin_rosiglitazone IN ('Up', 'Down') THEN 1 ELSE 0 END + CASE WHEN med_metformin_pioglitazone IN ('Up', 'Down') THEN 1 ELSE 0 END) AS n_meds_changed
  FROM ranked r JOIN first_enc f ON r.encounter_id = f.encounter_id
  WHERE r.rn = 1
)
SELECT
  r.encounter_id,
  r.patient_nbr,
  r.patient_encounter_seq,
  CASE WHEN r.patient_encounter_seq = 1 THEN 1 ELSE 0 END             AS is_first_encounter,
  r.race,
  r.gender,
  r.age_group,
  CAST(split_part(r.age_group, '-', 1) AS INT) + 5                     AS age_mid,
  r.weight_band,
  r.admission_type_id,
  r.discharge_disposition_id,
  r.admission_source_id,
  r.time_in_hospital,
  CASE WHEN r.time_in_hospital <= 2 THEN '01: 1-2 days'
       WHEN r.time_in_hospital <= 4 THEN '02: 3-4 days'
       WHEN r.time_in_hospital <= 7 THEN '03: 5-7 days'
       ELSE '04: 8-14 days' END                                       AS los_band,
  r.payer_code,
  r.medical_specialty,
  r.num_lab_procedures,
  r.num_procedures,
  r.num_medications,
  r.number_outpatient,
  r.number_emergency,
  r.number_inpatient,
  CASE WHEN r.number_inpatient = 0 THEN '0' WHEN r.number_inpatient = 1 THEN '1'
       WHEN r.number_inpatient = 2 THEN '2' ELSE '3+' END            AS prior_inpatient_band,
  r.number_outpatient + r.number_emergency + r.number_inpatient       AS prior_visits_total,
  r.diag_1, r.diag_2, r.diag_3,
  r.diag_1_group, r.diag_2_group, r.diag_3_group,
  r.number_diagnoses,
  r.max_glu_serum,
  r.a1c_result,
  r.med_metformin,
  r.med_repaglinide,
  r.med_nateglinide,
  r.med_chlorpropamide,
  r.med_glimepiride,
  r.med_acetohexamide,
  r.med_glipizide,
  r.med_glyburide,
  r.med_tolbutamide,
  r.med_pioglitazone,
  r.med_rosiglitazone,
  r.med_acarbose,
  r.med_miglitol,
  r.med_troglitazone,
  r.med_tolazamide,
  r.med_examide,
  r.med_citoglipton,
  r.med_insulin,
  r.med_glyburide_metformin,
  r.med_glipizide_metformin,
  r.med_glimepiride_pioglitazone,
  r.med_metformin_rosiglitazone,
  r.med_metformin_pioglitazone,
  r.n_diabetes_meds,
  r.n_meds_changed,
  r.med_change_flag,
  r.diabetes_med_flag,
  CASE WHEN r.med_insulin IN ('Steady', 'Up', 'Down') THEN 1 ELSE 0 END AS insulin_flag,
  r.readmitted,
  CASE WHEN r.readmitted = '<30' THEN 1 ELSE 0 END                    AS readmit_30d_flag,
  CASE WHEN r.readmitted IN ('<30', '>30') THEN 1 ELSE 0 END          AS readmit_any_flag,
  CASE WHEN r.discharge_disposition_id IN (11, 13, 14, 19, 20, 21) THEN 0 ELSE 1 END AS is_readmit_eligible,
  CASE WHEN r.num_medications > b.med_q3 + 3 * (b.med_q3 - b.med_q1) THEN 1 ELSE 0 END AS is_num_meds_outlier,
  CASE WHEN r.num_lab_procedures > b.lab_q3 + 3 * (b.lab_q3 - b.lab_q1) THEN 1 ELSE 0 END AS is_num_labs_outlier,
  CASE WHEN r.weight_band IS NULL THEN 1 ELSE 0 END                   AS dq_missing_weight,
  CASE WHEN r.race IS NULL THEN 1 ELSE 0 END                          AS dq_missing_race
FROM enriched r CROSS JOIN bounds b
WHERE r.patient_nbr IS NOT NULL
  AND r.readmitted IS NOT NULL
  AND r.gender IS NOT NULL
  AND r.age_group IS NOT NULL
  AND r.time_in_hospital BETWEEN 1 AND 14
  AND r.admission_type_id IS NOT NULL
  AND r.discharge_disposition_id IS NOT NULL
  AND r.admission_source_id IS NOT NULL;

-- COMMAND ----------

-- Long medication table: one row per encounter x prescribed diabetes drug (status Steady / Up / Down)

CREATE OR REPLACE TABLE cln_encounter_medications AS
SELECT encounter_id, 'metformin' AS medication, med_metformin AS dose_status FROM cln_encounters WHERE med_metformin IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'repaglinide' AS medication, med_repaglinide AS dose_status FROM cln_encounters WHERE med_repaglinide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'nateglinide' AS medication, med_nateglinide AS dose_status FROM cln_encounters WHERE med_nateglinide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'chlorpropamide' AS medication, med_chlorpropamide AS dose_status FROM cln_encounters WHERE med_chlorpropamide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'glimepiride' AS medication, med_glimepiride AS dose_status FROM cln_encounters WHERE med_glimepiride IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'acetohexamide' AS medication, med_acetohexamide AS dose_status FROM cln_encounters WHERE med_acetohexamide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'glipizide' AS medication, med_glipizide AS dose_status FROM cln_encounters WHERE med_glipizide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'glyburide' AS medication, med_glyburide AS dose_status FROM cln_encounters WHERE med_glyburide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'tolbutamide' AS medication, med_tolbutamide AS dose_status FROM cln_encounters WHERE med_tolbutamide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'pioglitazone' AS medication, med_pioglitazone AS dose_status FROM cln_encounters WHERE med_pioglitazone IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'rosiglitazone' AS medication, med_rosiglitazone AS dose_status FROM cln_encounters WHERE med_rosiglitazone IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'acarbose' AS medication, med_acarbose AS dose_status FROM cln_encounters WHERE med_acarbose IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'miglitol' AS medication, med_miglitol AS dose_status FROM cln_encounters WHERE med_miglitol IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'troglitazone' AS medication, med_troglitazone AS dose_status FROM cln_encounters WHERE med_troglitazone IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'tolazamide' AS medication, med_tolazamide AS dose_status FROM cln_encounters WHERE med_tolazamide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'examide' AS medication, med_examide AS dose_status FROM cln_encounters WHERE med_examide IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'citoglipton' AS medication, med_citoglipton AS dose_status FROM cln_encounters WHERE med_citoglipton IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'insulin' AS medication, med_insulin AS dose_status FROM cln_encounters WHERE med_insulin IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'glyburide_metformin' AS medication, med_glyburide_metformin AS dose_status FROM cln_encounters WHERE med_glyburide_metformin IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'glipizide_metformin' AS medication, med_glipizide_metformin AS dose_status FROM cln_encounters WHERE med_glipizide_metformin IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'glimepiride_pioglitazone' AS medication, med_glimepiride_pioglitazone AS dose_status FROM cln_encounters WHERE med_glimepiride_pioglitazone IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'metformin_rosiglitazone' AS medication, med_metformin_rosiglitazone AS dose_status FROM cln_encounters WHERE med_metformin_rosiglitazone IN ('Steady', 'Up', 'Down')
UNION ALL
SELECT encounter_id, 'metformin_pioglitazone' AS medication, med_metformin_pioglitazone AS dose_status FROM cln_encounters WHERE med_metformin_pioglitazone IN ('Steady', 'Up', 'Down');

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema (Spark SQL dialect)

CREATE OR REPLACE TABLE dim_admission_type AS
SELECT admission_type_id, description,
  CASE WHEN description IN ('NULL', 'Not Available', 'Not Mapped') THEN 'Unknown' ELSE description END AS admission_type
FROM (VALUES
  (1, 'Emergency'),
  (2, 'Urgent'),
  (3, 'Elective'),
  (4, 'Newborn'),
  (5, 'Not Available'),
  (6, 'NULL'),
  (7, 'Trauma Center'),
  (8, 'Not Mapped')
) AS t(admission_type_id, description);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_discharge_disposition AS
SELECT discharge_disposition_id, description,
  CASE WHEN discharge_disposition_id IN (11, 19, 20, 21) THEN 'Expired'
       WHEN discharge_disposition_id IN (13, 14) THEN 'Hospice'
       WHEN discharge_disposition_id = 1 THEN 'Home'
       WHEN discharge_disposition_id IN (6, 8) THEN 'Home with health service'
       WHEN discharge_disposition_id IN (3, 4, 15, 22, 23, 24, 27, 30) THEN 'Skilled nursing / rehab / long-term care'
       WHEN discharge_disposition_id IN (2, 5, 9, 10, 12, 16, 17, 28, 29) THEN 'Other hospital / institution'
       WHEN discharge_disposition_id = 7 THEN 'Left AMA'
       ELSE 'Unknown' END AS discharge_group,
  CASE WHEN discharge_disposition_id IN (11, 13, 14, 19, 20, 21) THEN 0 ELSE 1 END AS is_readmit_eligible
FROM (VALUES
  (1, 'Discharged to home'),
  (2, 'Discharged/transferred to another short term hospital'),
  (3, 'Discharged/transferred to SNF'),
  (4, 'Discharged/transferred to ICF'),
  (5, 'Discharged/transferred to another type of inpatient care institution'),
  (6, 'Discharged/transferred to home with home health service'),
  (7, 'Left AMA'),
  (8, 'Discharged/transferred to home under care of Home IV provider'),
  (9, 'Admitted as an inpatient to this hospital'),
  (10, 'Neonate discharged to another hospital for neonatal aftercare'),
  (11, 'Expired'),
  (12, 'Still patient or expected to return for outpatient services'),
  (13, 'Hospice / home'),
  (14, 'Hospice / medical facility'),
  (15, 'Discharged/transferred within this institution to Medicare approved swing bed'),
  (16, 'Discharged/transferred/referred another institution for outpatient services'),
  (17, 'Discharged/transferred/referred to this institution for outpatient services'),
  (18, 'NULL'),
  (19, 'Expired at home. Medicaid only, hospice.'),
  (20, 'Expired in a medical facility. Medicaid only, hospice.'),
  (21, 'Expired, place unknown. Medicaid only, hospice.'),
  (22, 'Discharged/transferred to another rehab fac including rehab units of a hospital .'),
  (23, 'Discharged/transferred to a long term care hospital.'),
  (24, 'Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.'),
  (25, 'Not Mapped'),
  (26, 'Unknown/Invalid'),
  (30, 'Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere'),
  (27, 'Discharged/transferred to a federal health care facility.'),
  (28, 'Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital'),
  (29, 'Discharged/transferred to a Critical Access Hospital (CAH).')
) AS t(discharge_disposition_id, description);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_admission_source AS
SELECT admission_source_id, description,
  CASE WHEN admission_source_id IN (1, 2, 3) THEN 'Referral'
       WHEN admission_source_id = 7 THEN 'Emergency room'
       WHEN admission_source_id IN (4, 5, 6, 10, 18, 19, 22, 25, 26) THEN 'Transfer'
       WHEN admission_source_id IN (9, 15, 17, 20, 21) THEN 'Unknown'
       ELSE 'Other' END AS admission_source_group
FROM (VALUES
  (1, 'Physician Referral'),
  (2, 'Clinic Referral'),
  (3, 'HMO Referral'),
  (4, 'Transfer from a hospital'),
  (5, 'Transfer from a Skilled Nursing Facility (SNF)'),
  (6, 'Transfer from another health care facility'),
  (7, 'Emergency Room'),
  (8, 'Court/Law Enforcement'),
  (9, 'Not Available'),
  (10, 'Transfer from critial access hospital'),
  (11, 'Normal Delivery'),
  (12, 'Premature Delivery'),
  (13, 'Sick Baby'),
  (14, 'Extramural Birth'),
  (15, 'Not Available'),
  (17, 'NULL'),
  (18, 'Transfer From Another Home Health Agency'),
  (19, 'Readmission to Same Home Health Agency'),
  (20, 'Not Mapped'),
  (21, 'Unknown/Invalid'),
  (22, 'Transfer from hospital inpt/same fac reslt in a sep claim'),
  (23, 'Born inside this hospital'),
  (24, 'Born outside this hospital'),
  (25, 'Transfer from Ambulatory Surgery Center'),
  (26, 'Transfer from Hospice')
) AS t(admission_source_id, description);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_medication AS
SELECT medication_key, medication, drug_class
FROM (VALUES
  (1, 'metformin', 'Biguanide'),
  (2, 'repaglinide', 'Meglitinide'),
  (3, 'nateglinide', 'Meglitinide'),
  (4, 'chlorpropamide', 'Sulfonylurea'),
  (5, 'glimepiride', 'Sulfonylurea'),
  (6, 'acetohexamide', 'Sulfonylurea'),
  (7, 'glipizide', 'Sulfonylurea'),
  (8, 'glyburide', 'Sulfonylurea'),
  (9, 'tolbutamide', 'Sulfonylurea'),
  (10, 'pioglitazone', 'Thiazolidinedione'),
  (11, 'rosiglitazone', 'Thiazolidinedione'),
  (12, 'acarbose', 'Alpha-glucosidase inhibitor'),
  (13, 'miglitol', 'Alpha-glucosidase inhibitor'),
  (14, 'troglitazone', 'Thiazolidinedione'),
  (15, 'tolazamide', 'Sulfonylurea'),
  (16, 'examide', 'Other (examide)'),
  (17, 'citoglipton', 'Other (citoglipton)'),
  (18, 'insulin', 'Insulin'),
  (19, 'glyburide_metformin', 'Combination'),
  (20, 'glipizide_metformin', 'Combination'),
  (21, 'glimepiride_pioglitazone', 'Combination'),
  (22, 'metformin_rosiglitazone', 'Combination'),
  (23, 'metformin_pioglitazone', 'Combination')
) AS t(medication_key, medication, drug_class);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_age_group AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY age_mid) AS INT) AS age_key, age_group, age_mid
FROM (SELECT DISTINCT age_group, age_mid FROM cln_encounters) a;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_diagnosis_group AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY diag_group) AS INT) AS diag_group_key, diag_group
FROM (SELECT diag_1_group AS diag_group FROM cln_encounters
      UNION SELECT diag_2_group FROM cln_encounters
      UNION SELECT diag_3_group FROM cln_encounters) d;

-- COMMAND ----------

-- Patient attributes are taken from the patient's first encounter (lowest encounter_id)

CREATE OR REPLACE TABLE dim_patient AS
SELECT patient_nbr, race, gender, age_group AS first_age_group, n_encounters
FROM (
  SELECT patient_nbr, race, gender, age_group,
         COUNT(*) OVER (PARTITION BY patient_nbr) AS n_encounters,
         ROW_NUMBER() OVER (PARTITION BY patient_nbr ORDER BY encounter_id) AS rn
  FROM cln_encounters
) p WHERE rn = 1;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_encounter AS
SELECT
  e.encounter_id,
  e.patient_nbr,
  a.age_key,
  d1.diag_group_key AS primary_diag_group_key,
  d2.diag_group_key AS secondary_diag_group_key,
  e.admission_type_id,
  e.discharge_disposition_id,
  e.admission_source_id,
  e.patient_encounter_seq,
  e.is_first_encounter,
  e.payer_code,
  e.medical_specialty,
  e.diag_1,
  e.time_in_hospital,
  e.los_band,
  e.num_lab_procedures,
  e.num_procedures,
  e.num_medications,
  e.number_outpatient,
  e.number_emergency,
  e.number_inpatient,
  e.prior_inpatient_band,
  e.number_diagnoses,
  e.max_glu_serum,
  e.a1c_result,
  e.n_diabetes_meds,
  e.n_meds_changed,
  e.med_change_flag,
  e.diabetes_med_flag,
  e.insulin_flag,
  e.med_insulin AS insulin_status,
  e.readmitted,
  e.readmit_30d_flag,
  e.readmit_any_flag,
  e.is_readmit_eligible,
  e.is_num_meds_outlier,
  e.is_num_labs_outlier
FROM cln_encounters e
JOIN dim_age_group a ON e.age_group = a.age_group
JOIN dim_diagnosis_group d1 ON e.diag_1_group = d1.diag_group
JOIN dim_diagnosis_group d2 ON e.diag_2_group = d2.diag_group;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_encounter_medication AS
SELECT m.encounter_id, dm.medication_key, m.dose_status,
       f.readmit_30d_flag, f.readmit_any_flag, f.is_readmit_eligible
FROM cln_encounter_medications m
JOIN dim_medication dm ON m.medication = dm.medication
JOIN fact_encounter f ON m.encounter_id = f.encounter_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPIs (Spark SQL dialect)

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  COUNT(*)                                                                    AS encounters_total,
  COUNT(DISTINCT patient_nbr)                                                 AS patients_total,
  SUM(is_readmit_eligible)                                                    AS eligible_encounters,
  SUM(CASE WHEN is_readmit_eligible = 1 THEN readmit_30d_flag ELSE 0 END)     AS readmits_30d,
  ROUND(100.0 * SUM(CASE WHEN is_readmit_eligible = 1 THEN readmit_30d_flag ELSE 0 END) / SUM(is_readmit_eligible), 2) AS readmit_30d_pct,
  ROUND(100.0 * SUM(CASE WHEN is_readmit_eligible = 1 THEN readmit_any_flag ELSE 0 END) / SUM(is_readmit_eligible), 2) AS readmit_any_pct,
  ROUND(100.0 * SUM(readmit_30d_flag) / COUNT(*), 2)                          AS readmit_30d_pct_all_encounters,
  ROUND(100.0 * SUM(CASE WHEN is_readmit_eligible = 1 AND is_first_encounter = 1 THEN readmit_30d_flag ELSE 0 END)
        / SUM(CASE WHEN is_readmit_eligible = 1 AND is_first_encounter = 1 THEN 1 ELSE 0 END), 2) AS readmit_30d_pct_first_encounter,
  ROUND(AVG(time_in_hospital), 2)                                             AS avg_los_days,
  ROUND(AVG(num_medications), 2)                                              AS avg_num_medications,
  ROUND(AVG(num_lab_procedures), 2)                                           AS avg_num_lab_procedures,
  ROUND(100.0 * SUM(med_change_flag) / COUNT(*), 2)                           AS med_change_pct,
  ROUND(100.0 * SUM(diabetes_med_flag) / COUNT(*), 2)                         AS on_diabetes_med_pct,
  ROUND(100.0 * SUM(insulin_flag) / COUNT(*), 2)                              AS on_insulin_pct,
  ROUND(100.0 * SUM(CASE WHEN a1c_result <> 'Not measured' THEN 1 ELSE 0 END) / COUNT(*), 2) AS a1c_tested_pct,
  ROUND(100.0 * SUM(CASE WHEN number_inpatient > 0 THEN 1 ELSE 0 END) / COUNT(*), 2) AS prior_inpatient_pct
FROM fact_encounter;

-- COMMAND ----------

-- Q1 readmission by age group

CREATE OR REPLACE TABLE a_readmit_by_age AS
SELECT a.age_group, a.age_mid,
       COUNT(*) AS encounters,
       SUM(f.readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(f.readmit_30d_flag), 2) AS readmit_30d_pct,
       ROUND(100.0 * AVG(f.readmit_any_flag), 2) AS readmit_any_pct,
       ROUND(AVG(f.time_in_hospital), 2) AS avg_los_days
FROM fact_encounter f JOIN dim_age_group a ON f.age_key = a.age_key
WHERE f.is_readmit_eligible = 1
GROUP BY a.age_group, a.age_mid;

-- COMMAND ----------

-- Q2 readmission by primary diagnosis group (ICD-9 chapters)

CREATE OR REPLACE TABLE a_readmit_by_diagnosis AS
SELECT d.diag_group AS primary_diagnosis_group,
       COUNT(*) AS encounters,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS share_pct,
       SUM(f.readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(f.readmit_30d_flag), 2) AS readmit_30d_pct,
       ROUND(100.0 * AVG(f.readmit_any_flag), 2) AS readmit_any_pct,
       ROUND(AVG(f.time_in_hospital), 2) AS avg_los_days
FROM fact_encounter f JOIN dim_diagnosis_group d ON f.primary_diag_group_key = d.diag_group_key
WHERE f.is_readmit_eligible = 1
GROUP BY d.diag_group;

-- COMMAND ----------

-- Q2b top 15 primary ICD-9 codes by volume

CREATE OR REPLACE TABLE a_readmit_top_diag_codes AS
SELECT diag_1, encounters, readmit_30d_pct FROM (
  SELECT diag_1, COUNT(*) AS encounters, ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct,
         ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC, diag_1) AS rk
  FROM fact_encounter WHERE is_readmit_eligible = 1 AND diag_1 IS NOT NULL
  GROUP BY diag_1) t
WHERE rk <= 15;

-- COMMAND ----------

-- Q3 readmission by length of stay (days 1-14) and band

CREATE OR REPLACE TABLE a_readmit_by_los AS
SELECT time_in_hospital AS los_days, los_band,
       COUNT(*) AS encounters,
       SUM(readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct,
       ROUND(100.0 * AVG(readmit_any_flag), 2) AS readmit_any_pct
FROM fact_encounter WHERE is_readmit_eligible = 1
GROUP BY time_in_hospital, los_band;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_readmit_by_los_band AS
SELECT los_band, COUNT(*) AS encounters, SUM(readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct,
       ROUND(AVG(num_medications), 2) AS avg_num_medications
FROM fact_encounter WHERE is_readmit_eligible = 1
GROUP BY los_band;

-- COMMAND ----------

-- Q4 medications: readmission among encounters where each drug was prescribed (>= 500 encounters)

CREATE OR REPLACE TABLE a_readmit_by_medication AS
SELECT dm.medication, dm.drug_class,
       COUNT(*) AS encounters_prescribed,
       SUM(CASE WHEN m.dose_status IN ('Up', 'Down') THEN 1 ELSE 0 END) AS encounters_dose_changed,
       SUM(m.readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(m.readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter_medication m JOIN dim_medication dm ON m.medication_key = dm.medication_key
WHERE m.is_readmit_eligible = 1
GROUP BY dm.medication, dm.drug_class
HAVING COUNT(*) >= 500;

-- COMMAND ----------

-- Q4b insulin dose status, medication change and number of diabetes drugs

CREATE OR REPLACE TABLE a_readmit_by_insulin AS
SELECT insulin_status, COUNT(*) AS encounters, ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter WHERE is_readmit_eligible = 1 GROUP BY insulin_status;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_readmit_by_med_change AS
SELECT CASE WHEN diabetes_med_flag = 1 THEN 'On diabetes med' ELSE 'No diabetes med' END AS diabetes_med,
       CASE WHEN med_change_flag = 1 THEN 'Changed' ELSE 'Not changed' END AS med_change,
       COUNT(*) AS encounters, ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter WHERE is_readmit_eligible = 1 GROUP BY 1, 2;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_readmit_by_n_meds AS
SELECT CASE WHEN n_diabetes_meds >= 3 THEN '3+' ELSE CAST(n_diabetes_meds AS STRING) END AS n_diabetes_meds,
       COUNT(*) AS encounters, ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter WHERE is_readmit_eligible = 1 GROUP BY 1;

-- COMMAND ----------

-- Q5 other drivers: prior inpatient visits, HbA1c test, discharge destination, admission type

CREATE OR REPLACE TABLE a_readmit_by_prior_inpatient AS
SELECT prior_inpatient_band, COUNT(*) AS encounters, SUM(readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter WHERE is_readmit_eligible = 1 GROUP BY prior_inpatient_band;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_readmit_by_a1c AS
SELECT a1c_result, COUNT(*) AS encounters, ROUND(100.0 * AVG(readmit_30d_flag), 2) AS readmit_30d_pct,
       ROUND(100.0 * AVG(med_change_flag), 2) AS med_change_pct
FROM fact_encounter WHERE is_readmit_eligible = 1 GROUP BY a1c_result;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_readmit_by_discharge AS
SELECT d.discharge_group, COUNT(*) AS encounters, SUM(f.readmit_30d_flag) AS readmits_30d,
       ROUND(100.0 * AVG(f.readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter f JOIN dim_discharge_disposition d ON f.discharge_disposition_id = d.discharge_disposition_id
GROUP BY d.discharge_group;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_readmit_by_admission_type AS
SELECT t.admission_type, COUNT(*) AS encounters, ROUND(100.0 * AVG(f.readmit_30d_flag), 2) AS readmit_30d_pct
FROM fact_encounter f JOIN dim_admission_type t ON f.admission_type_id = t.admission_type_id
WHERE f.is_readmit_eligible = 1 GROUP BY t.admission_type;

-- COMMAND ----------

-- Q6 patients: repeat users drive volume

CREATE OR REPLACE TABLE a_patient_utilisation AS
SELECT CASE WHEN n_encounters >= 5 THEN '5+' ELSE CAST(n_encounters AS STRING) END AS encounters_per_patient,
       COUNT(*) AS patients, SUM(n_encounters) AS encounters,
       ROUND(100.0 * SUM(n_encounters) / SUM(SUM(n_encounters)) OVER (), 2) AS encounter_share_pct
FROM dim_patient GROUP BY 1;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence (Spark SQL dialect)

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'encounters' AS entity,
       (SELECT COUNT(*) FROM stg_encounters) AS raw_rows,
       (SELECT COUNT(DISTINCT encounter_id) FROM stg_encounters) AS distinct_keys,
       (SELECT COUNT(*) FROM cln_encounters) AS clean_rows,
       'encounter_id' AS grain
UNION ALL SELECT 'encounter_medications', NULL, NULL, (SELECT COUNT(*) FROM cln_encounter_medications), 'encounter x prescribed drug'
UNION ALL SELECT 'fact_encounter', NULL, NULL, (SELECT COUNT(*) FROM fact_encounter), 'encounter'
UNION ALL SELECT 'fact_encounter_medication', NULL, NULL, (SELECT COUNT(*) FROM fact_encounter_medication), 'encounter x drug'
UNION ALL SELECT 'dim_patient', NULL, NULL, (SELECT COUNT(*) FROM dim_patient), 'patient_nbr'
UNION ALL SELECT 'dim_age_group', NULL, NULL, (SELECT COUNT(*) FROM dim_age_group), 'age decade'
UNION ALL SELECT 'dim_diagnosis_group', NULL, NULL, (SELECT COUNT(*) FROM dim_diagnosis_group), 'ICD-9 group'
UNION ALL SELECT 'dim_admission_type', NULL, NULL, (SELECT COUNT(*) FROM dim_admission_type), 'admission_type_id'
UNION ALL SELECT 'dim_discharge_disposition', NULL, NULL, (SELECT COUNT(*) FROM dim_discharge_disposition), 'discharge_disposition_id'
UNION ALL SELECT 'dim_admission_source', NULL, NULL, (SELECT COUNT(*) FROM dim_admission_source), 'admission_source_id'
UNION ALL SELECT 'dim_medication', NULL, NULL, (SELECT COUNT(*) FROM dim_medication), 'drug';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'encounters' AS entity, 'weight' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN weight = '?' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM stg_encounters) AS raw_missing_pct,
  (SELECT ROUND(100.0 * SUM(dq_missing_weight) / COUNT(*), 2) FROM cln_encounters) AS clean_null_pct,
  'kept as NULL (97% missing - not used for analysis)' AS treatment
UNION ALL SELECT 'encounters', 'payer_code',
  (SELECT ROUND(100.0 * SUM(CASE WHEN payer_code = '?' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM stg_encounters),
  (SELECT ROUND(100.0 * SUM(CASE WHEN payer_code IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) FROM cln_encounters),
  'kept as NULL'
UNION ALL SELECT 'encounters', 'medical_specialty',
  (SELECT ROUND(100.0 * SUM(CASE WHEN medical_specialty = '?' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM stg_encounters),
  (SELECT ROUND(100.0 * SUM(CASE WHEN medical_specialty IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) FROM cln_encounters),
  'kept as NULL'
UNION ALL SELECT 'encounters', 'race',
  (SELECT ROUND(100.0 * SUM(CASE WHEN race = '?' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM stg_encounters),
  (SELECT ROUND(100.0 * SUM(dq_missing_race) / COUNT(*), 2) FROM cln_encounters),
  'kept as NULL'
UNION ALL SELECT 'encounters', 'diag_1',
  (SELECT ROUND(100.0 * SUM(CASE WHEN diag_1 = '?' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM stg_encounters),
  (SELECT ROUND(100.0 * SUM(CASE WHEN diag_1 IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) FROM cln_encounters),
  'NULL -> diagnosis group Missing'
UNION ALL SELECT 'encounters', 'A1Cresult',
  (SELECT ROUND(100.0 * SUM(CASE WHEN A1Cresult = 'None' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM stg_encounters),
  (SELECT ROUND(100.0 * SUM(CASE WHEN a1c_result = 'Not measured' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM cln_encounters),
  '''None'' means test not done -> category Not measured';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'encounters: duplicate encounter_id (extras dropped)' AS check_name,
       (SELECT COUNT(*) - COUNT(DISTINCT encounter_id) FROM stg_encounters) AS affected_rows
UNION ALL SELECT 'encounters: gender Unknown/Invalid (dropped)',
       (SELECT COUNT(*) FROM stg_encounters WHERE gender NOT IN ('Male', 'Female'))
UNION ALL SELECT 'encounters: rows dropped in cleaning',
       (SELECT COUNT(*) FROM stg_encounters) - (SELECT COUNT(*) FROM cln_encounters)
UNION ALL SELECT 'encounters: expired / hospice discharge (excluded from readmission rates)',
       (SELECT COUNT(*) FROM cln_encounters WHERE is_readmit_eligible = 0)
UNION ALL SELECT 'encounters: repeat encounters of the same patient',
       (SELECT COUNT(*) FROM cln_encounters WHERE is_first_encounter = 0)
UNION ALL SELECT 'encounters: num_medications outlier (> Q3 + 3*IQR, kept)', (SELECT SUM(is_num_meds_outlier) FROM cln_encounters)
UNION ALL SELECT 'encounters: num_lab_procedures outlier (> Q3 + 3*IQR, kept)', (SELECT SUM(is_num_labs_outlier) FROM cln_encounters)
UNION ALL SELECT 'encounters: diag_1 is a V/E supplementary code', (SELECT COUNT(*) FROM cln_encounters WHERE diag_1 LIKE 'V%' OR diag_1 LIKE 'E%')
UNION ALL SELECT 'encounters: discharge id not in IDS_mapping', (SELECT COUNT(*) FROM cln_encounters WHERE discharge_disposition_id NOT IN (SELECT discharge_disposition_id FROM dim_discharge_disposition))
UNION ALL SELECT 'encounters: patients with > 1 encounter', (SELECT COUNT(*) FROM dim_patient WHERE n_encounters > 1);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_encounter.encounter_id unique' AS check_name,
         (SELECT COUNT(*) - COUNT(DISTINCT encounter_id) FROM fact_encounter) AS failed_rows
  UNION ALL SELECT 'fact_encounter rows = cln_encounters rows',
         (SELECT ABS((SELECT COUNT(*) FROM fact_encounter) - (SELECT COUNT(*) FROM cln_encounters)))
  UNION ALL SELECT 'fact_encounter.patient_nbr -> dim_patient',
         (SELECT COUNT(*) FROM fact_encounter WHERE patient_nbr NOT IN (SELECT patient_nbr FROM dim_patient))
  UNION ALL SELECT 'fact_encounter.admission_type_id -> dim_admission_type',
         (SELECT COUNT(*) FROM fact_encounter WHERE admission_type_id NOT IN (SELECT admission_type_id FROM dim_admission_type))
  UNION ALL SELECT 'fact_encounter.discharge_disposition_id -> dim_discharge_disposition',
         (SELECT COUNT(*) FROM fact_encounter WHERE discharge_disposition_id NOT IN (SELECT discharge_disposition_id FROM dim_discharge_disposition))
  UNION ALL SELECT 'fact_encounter.admission_source_id -> dim_admission_source',
         (SELECT COUNT(*) FROM fact_encounter WHERE admission_source_id NOT IN (SELECT admission_source_id FROM dim_admission_source))
  UNION ALL SELECT 'fact_encounter_medication.medication_key -> dim_medication',
         (SELECT COUNT(*) FROM fact_encounter_medication WHERE medication_key NOT IN (SELECT medication_key FROM dim_medication))
  UNION ALL SELECT 'seeded lookup rows exist verbatim in IDS_mapping.csv',
         (SELECT COUNT(*) FROM (
            SELECT CAST(admission_type_id AS STRING) AS id, description FROM dim_admission_type
            UNION ALL SELECT CAST(discharge_disposition_id AS STRING), description FROM dim_discharge_disposition
            UNION ALL SELECT CAST(admission_source_id AS STRING), description FROM dim_admission_source) s
          WHERE NOT EXISTS (SELECT 1 FROM stg_ids_mapping m
                            WHERE trim(m.admission_type_id) = s.id AND trim(m.description) = s.description))
  UNION ALL SELECT 'readmitted in {<30, >30, NO}',
         (SELECT COUNT(*) FROM fact_encounter WHERE readmitted NOT IN ('<30', '>30', 'NO'))
  UNION ALL SELECT 'time_in_hospital between 1 and 14',
         (SELECT COUNT(*) FROM fact_encounter WHERE time_in_hospital NOT BETWEEN 1 AND 14)
  UNION ALL SELECT 'readmit_30d_flag <= readmit_any_flag',
         (SELECT COUNT(*) FROM fact_encounter WHERE readmit_30d_flag > readmit_any_flag)
  UNION ALL SELECT 'non-negative visit / medication counts',
         (SELECT COUNT(*) FROM fact_encounter WHERE num_medications < 0 OR number_inpatient < 0 OR number_emergency < 0 OR number_outpatient < 0)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Quality summary
-- MAGIC All assertions should be PASS.

-- COMMAND ----------

SELECT * FROM dq_row_counts;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visualizations
-- MAGIC The same views are pre-built in `readmissions_dashboard.lvdash.json` (published as **da-learn-08 Hospital readmissions**).

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization dataset: Headline KPIs
SELECT encounters_total, patients_total, readmit_30d_pct / 100 AS readmit_30d_rate, readmit_any_pct / 100 AS readmit_any_rate, avg_los_days FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization dataset: By age
SELECT age_group, age_mid, encounters, readmit_30d_pct FROM a_readmit_by_age ORDER BY age_mid;

-- COMMAND ----------

-- Visualization dataset: By diagnosis
SELECT primary_diagnosis_group, encounters, readmit_30d_pct FROM a_readmit_by_diagnosis ORDER BY readmit_30d_pct DESC;

-- COMMAND ----------

-- Visualization dataset: By length of stay
SELECT los_days, encounters, readmit_30d_pct FROM a_readmit_by_los ORDER BY los_days;

-- COMMAND ----------

-- Visualization dataset: By medication
SELECT medication, encounters_prescribed, readmit_30d_pct FROM a_readmit_by_medication ORDER BY readmit_30d_pct DESC;

-- COMMAND ----------

-- Visualization dataset: By prior inpatient visits
SELECT prior_inpatient_band, encounters, readmit_30d_pct FROM a_readmit_by_prior_inpatient ORDER BY prior_inpatient_band;

-- COMMAND ----------

-- Visualization dataset: By discharge destination
SELECT discharge_group, encounters, readmit_30d_pct FROM a_readmit_by_discharge ORDER BY readmit_30d_pct DESC;
