#!/usr/bin/env python3
"""Generate the Databricks SQL notebook (databricks/<nb>.sql) and Lakeview dashboard JSON from sql/02-05 + scripts/project.py.
Usage: python scripts/build_databricks.py"""
import importlib.util, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
spec = importlib.util.spec_from_file_location("project", ROOT / "scripts" / "project.py")
P = importlib.util.module_from_spec(spec); spec.loader.exec_module(P)
import lakeview

D = P.DBX
CATALOG, SCHEMA = "workspace", D["schema"]
VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/raw"
SEP = "\n\n-- COMMAND ----------\n\n"


def md(text):
    return "\n".join(["-- MAGIC %md"] + [f"-- MAGIC {l}".rstrip() for l in text.strip().splitlines()])


def statements(path):
    out, buf = [], []
    for line in path.read_text().splitlines():
        buf.append(line)
        code = line.split("--")[0] if ("--" in line and line[:line.find("--")].count("'") % 2 == 0) else line
        if code.rstrip().endswith(";"):
            keep = [l for l in buf if not l.strip().startswith("--")]
            head = next((l for l in buf if l.strip().startswith("--")), None)
            s = "\n".join(([head] if head else []) + keep).strip()
            if any(l.strip() and not l.strip().startswith("--") for l in s.splitlines()):
                out.append(s)
            buf = []
    return out


def notebook():
    cells = ["-- Databricks notebook source\n" + md(f"""
# {D['title']} - SQL pipeline (Databricks SQL)
Generated by `scripts/build_databricks.py` from `sql/` and executed on a serverless SQL warehouse by `scripts/databricks_deploy.py`.

1. Upload the raw file(s) to the Unity Catalog volume `{VOLUME}` (see `databricks/SETUP.md`).
2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
3. Cells: config -> 01 staging (`read_files`, all STRING) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.""")]
    cells.append(f"-- Config: change catalog / schema here (and in the dashboard JSON) if needed\n"
                 f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA};\nUSE CATALOG {CATALOG};\nUSE SCHEMA {SCHEMA};")
    cells.append(md("## 01 Staging - all columns as STRING (`inferColumnTypes => false`); casting happens in 02"))
    for t, (f, extra, sel) in D["staging"].items():
        opts = "format => 'csv', header => true, multiLine => true, escape => '\"', inferColumnTypes => false" + (", " + extra if extra else "")
        cells.append(f"CREATE OR REPLACE TABLE {t} AS\nSELECT {sel or '*'}\nFROM read_files('{VOLUME}/{f}',\n  {opts});")
    titles = {"02_cleaning.sql": "02 Cleaning", "03_model.sql": "03 Star schema", "04_analysis.sql": "04 Business KPIs",
              "05_quality_checks.sql": "05 Data-quality checks"}
    for f, title in titles.items():
        cells.append(md(f"## {title} (`sql/{f}`)"))
        cells += statements(ROOT / "sql" / f)
    cells.append(md("## Quality summary\nAll assertions should be PASS."))
    cells.append("SELECT * FROM dq_row_counts;")
    cells.append("SELECT * FROM dq_assertions ORDER BY status, check_name;")
    cells.append(md(f"## Visualizations\nThe same views are pre-built in `{D['dashboard_file']}` (published as **{D['dashboard_name']}**)."))
    cells.append("SELECT * FROM a_kpi_headline;")
    for d in P.dashboard_def(lambda t: t)["datasets"]:
        cells.append(f"-- Visualization dataset: {d['displayName']}\n{d['queryLines'][0]};")
    return SEP.join(cells) + "\n"


if __name__ == "__main__":
    out = ROOT / "databricks"; out.mkdir(exist_ok=True)
    (out / D["notebook_file"]).write_text(notebook())
    dash = P.dashboard_def(lambda t: f"{CATALOG}.{SCHEMA}.{t}")
    (out / D["dashboard_file"]).write_text(json.dumps(dash, indent=1) + "\n")
    print("wrote", D["notebook_file"], D["dashboard_file"], "visuals:", lakeview.count_visuals(dash))
